//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballDataOrgDataSource.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FootballDataOrgDataSource.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: { &quot;href&quot;: &quot;http://api.football-data.org/v1/teams/61/fixtures&quot; },
        ///    &quot;team&quot;: { &quot;href&quot;: &quot;http://api.football-data.org/v1/teams/61&quot; }
        ///  },
        ///  &quot;timeFrameStart&quot;: &quot;2016-07-10&quot;,
        ///  &quot;timeFrameEnd&quot;: &quot;2016-08-13&quot;,
        ///  &quot;count&quot;: 1,
        ///  &quot;fixtures&quot;: [
        ///    {
        ///      &quot;_links&quot;: {
        ///        &quot;self&quot;: { &quot;href&quot;: &quot;http://api.football-data.org/v1/fixtures/150838&quot; },
        ///        &quot;competition&quot;: { &quot;href&quot;: &quot;http://api.football-data.org/v1/competitions/426&quot; },
        ///        &quot;homeTeam&quot;: { &quot;href&quot;: &quot;http://api.footba [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nextFixture_json {
            get {
                return ResourceManager.GetString("nextFixture_json", resourceCulture);
            }
        }
    }
}
